/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
export namespace Components {
    interface AppHome {
        "areas": { type: string; ratings: { Walls: string; Ceiling: string; Floor: string; 'Doors and/or windows': string; Lighting: string; Cleaning: string; Bath: string; Shower: string; 'Wash basin': string; }; photos: { Walls: any[]; Ceiling: any[]; Floor: any[]; 'Doors and/or windows': any[]; Lighting: any[]; Cleaning: any[]; Bath: any[]; Shower: any[]; 'Wash basin': any[]; }; }[];
        "keys": { type: string; amount: number; }[];
        "readingsElectricity": { type: string; value: number; photos: any[]; }[];
        "readingsGas": { type: string; value: number; photos: any[]; }[];
        "readingsWater": { type: string; value: number; photos: any[]; }[];
        "repairs": { name: string; phone: string; description: string; toBePaidBy: string; photos: any[]; }[];
    }
    interface AppPhoto {
        "imageData": any;
        "text": string;
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppPhotoElement extends Components.AppPhoto, HTMLStencilElement {
    }
    var HTMLAppPhotoElement: {
        prototype: HTMLAppPhotoElement;
        new (): HTMLAppPhotoElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-photo": HTMLAppPhotoElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
        "areas"?: { type: string; ratings: { Walls: string; Ceiling: string; Floor: string; 'Doors and/or windows': string; Lighting: string; Cleaning: string; Bath: string; Shower: string; 'Wash basin': string; }; photos: { Walls: any[]; Ceiling: any[]; Floor: any[]; 'Doors and/or windows': any[]; Lighting: any[]; Cleaning: any[]; Bath: any[]; Shower: any[]; 'Wash basin': any[]; }; }[];
        "keys"?: { type: string; amount: number; }[];
        "readingsElectricity"?: { type: string; value: number; photos: any[]; }[];
        "readingsGas"?: { type: string; value: number; photos: any[]; }[];
        "readingsWater"?: { type: string; value: number; photos: any[]; }[];
        "repairs"?: { name: string; phone: string; description: string; toBePaidBy: string; photos: any[]; }[];
    }
    interface AppPhoto {
        "imageData"?: any;
        "onImageSelected"?: (event: CustomEvent<any>) => void;
        "text"?: string;
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-photo": AppPhoto;
        "app-profile": AppProfile;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-photo": LocalJSX.AppPhoto & JSXBase.HTMLAttributes<HTMLAppPhotoElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
